### ISSUE TITLE
error with fawe

### ISSUE THREAD

**Issue by ConnorServers** [CatalysmRL/CataMines#9]
`[08:40:55 WARN]: [CataMines] Task #184 for CataMines v2.5.11 generated an exception
java.lang.NoClassDefFoundError: io/papermc/paper/util/MCUtil
        at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R1.PaperweightPlatformAdapter.addTicket(PaperweightPlatformAdapter.java:300) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-464.jar:?]
        at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R1.PaperweightPlatformAdapter.ensureLoaded(PaperweightPlatformAdapter.java:275) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-464.jar:?]
        at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R1.PaperweightGetBlocks.ensureLoaded(PaperweightGetBlocks.java:382) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-464.jar:?]
        at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R1.PaperweightGetBlocks.getChunk(PaperweightGetBlocks.java:1026) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-464.jar:?]
        at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R1.PaperweightGetBlocks.getSections(PaperweightGetBlocks.java:1008) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-464.jar:?]
        at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R1.PaperweightGetBlocks.hasSection(PaperweightGetBlocks.java:1113) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-464.jar:?]
        at com.fastasyncworldedit.core.extent.processor.heightmap.HeightmapProcessor.processSet(HeightmapProcessor.java:60) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-464.jar:?]
        at com.fastasyncworldedit.core.extent.processor.MultiBatchProcessor.processSet(MultiBatchProcessor.java:126) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-464.jar:?]
        at com.fastasyncworldedit.core.extent.processor.MultiBatchProcessor.processSet(MultiBatchProcessor.java:106) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-464.jar:?]
        at com.fastasyncworldedit.core.extent.processor.BatchProcessorHolder.processSet(BatchProcessorHolder.java:27) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-464.jar:?]
        at com.fastasyncworldedit.core.queue.implementation.chunk.ChunkHolder.call(ChunkHolder.java:1066) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-464.jar:?]
        at com.fastasyncworldedit.core.queue.implementation.chunk.ChunkHolder.call(ChunkHolder.java:1047) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-464.jar:?]
        at com.fastasyncworldedit.core.queue.implementation.SingleThreadQueueExtent.submitUnchecked(SingleThreadQueueExtent.java:242) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-464.jar:?]
        at com.fastasyncworldedit.core.queue.implementation.SingleThreadQueueExtent.flush(SingleThreadQueueExtent.java:462) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-464.jar:?]
        at com.fastasyncworldedit.core.queue.IQueueExtent.commit(IQueueExtent.java:104) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-464.jar:?]
        at com.fastasyncworldedit.core.extent.PassthroughExtent.commit(PassthroughExtent.java:221) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-464.jar:?]
        at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:1275) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-464.jar:?]
        at com.sk89q.worldedit.EditSession.close(EditSession.java:1215) ~[FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-464.jar:?]
        at de.c4t4lysm.catamines.utils.mine.AbstractCataMine.reset(AbstractCataMine.java:163) ~[CataMines-2.5.11.jar:?]
        at de.c4t4lysm.catamines.utils.mine.AbstractCataMine.forceReset(AbstractCataMine.java:172) ~[CataMines-2.5.11.jar:?]
        at de.c4t4lysm.catamines.utils.mine.AbstractCataMine.run(AbstractCataMine.java:103) ~[CataMines-2.5.11.jar:?]
        at de.c4t4lysm.catamines.schedulers.MineManager.run(MineManager.java:42) ~[CataMines-2.5.11.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.19.2.jar:git-Pufferfish-35]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[pufferfish-1.19.2.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1495) ~[pufferfish-1.19.2.jar:git-Pufferfish-35]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[pufferfish-1.19.2.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1419) ~[pufferfish-1.19.2.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[pufferfish-1.19.2.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[pufferfish-1.19.2.jar:git-Pufferfish-35]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.papermc.paper.util.MCUtil
        ... 30 more`

**Comment by CatalysmRL** [comment]
I would suggest updating fawe or your server implementation. I heard that some paper version are not supported
